__author__ = 'singo'
__datetime__ = '2019/5/7 11:03 AM'

__all__ = ['UNREVIEWED', 'PRO', 'ONLINE', 'STAY_ONLINE', 'PRE', 'ROLLBACK', 'ONLINEING',
           'TEST', 'REONLONE', 'ONLINED', 'REJECT', 'FAIL', 'FAILED', 'CANCELED',
           'UNKNOWN', 'SUCCESSFUL']

UNREVIEWED = PRO = ONLINE = SUCCESSFUL = 0
STAY_ONLINE = PRE = ROLLBACK = FAILED = 1
ONLINEING = TEST = REONLONE = CANCELED = 2
ONLINED = UNKNOWN = 3
REJECT = 4
FAIL= 5



