data = {'return':
            [
                {'devops':
                     {'biosversion': 'VirtualBox',
                      'kernel': 'Linux',
                      'domain': '',
                      'uid': 0,
                      'zmqversion': '3.2.5',
                      'kernelrelease': '3.10.0-327.4.5.el7.x86_64',
                      'selinux': {'enforced': 'Disabled', 'enabled': False},
                      'serialnumber': '0', 'pid': 3402,
                      'ip_interfaces': {
                          'lo': ['127.0.0.1', '::1'],
                          'enp0s3': ['10.0.2.15', 'fe80::a00:27ff:fe6c:3e95'],
                          'enp0s8': ['192.168.33.20', 'fe80::a00:27ff:feaf:7437']},
                      'groupname': 'root',
                      'fqdn_ip6': [],
                      'mem_total': 237,
                      'saltversioninfo': [2018, 3, 3, 0],
                      'zfs_support': False,
                      'SSDs': [],
                      'mdadm': [],
                      'id': 'devops',
                      'osrelease': '7.2.1511',
                      'ps': 'ps -efHww',
                      'systemd': {'version': '219', 'features': '+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN'},
                      'fqdn': 'devops',
                      'ip_gw': True,
                      'ip6_interfaces': {'lo': ['::1'], 'enp0s3': ['fe80::a00:27ff:fe6c:3e95'],
                                         'enp0s8': ['fe80::a00:27ff:feaf:7437']},
                      'num_cpus': 2,
                      'hwaddr_interfaces': {'lo': '00:00:00:00:00:00', 'enp0s3': '08:00:27:6c:3e:95', 'enp0s8': '08:00:27:af:74:37'},
                      'osfullname': 'CentOS Linux',
                      'ip4_interfaces': {'lo': ['127.0.0.1'],
                                         'enp0s3': ['10.0.2.15'],
                                         'enp0s8': ['192.168.33.20']},
                      'init': 'systemd',
                      'gid': 0, 'master': '10.0.2.15',
                      'ipv4': ['10.0.2.15', '127.0.0.1', '192.168.33.20'],
                      'dns': {'domain': '', 'sortlist': [], 'nameservers': ['10.0.2.3'], 'ip4_nameservers': ['10.0.2.3'], 'search': [], 'ip6_nameservers': [], 'options': []},
                      'ipv6': ['::1', 'fe80::a00:27ff:fe6c:3e95', 'fe80::a00:27ff:feaf:7437'],
                      'virtual': 'VirtualBox',
                      'cpu_flags': ['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ht', 'syscall', 'nx', 'rdtscp', 'lm', 'constant_tsc', 'rep_good', 'nopl', 'xtopology', 'nonstop_tsc', 'pni', 'pclmulqdq', 'ssse3', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'movbe', 'popcnt', 'aes', 'xsave', 'avx', 'rdrand', 'lahf_lm', 'abm', '3dnowprefetch', 'fsgsbase', 'avx2', 'invpcid', 'rdseed', 'clflushopt'],
                      'localhost': 'devops',
                      'lsb_distrib_id': 'CentOS Linux',
                      'username': 'root',
                      'fqdn_ip4': ['127.0.0.1'],
                      'shell': '/bin/sh',
                      'nodename': 'devops',
                      'saltversion': '2018.3.3',
                      'ip6_gw': False,
                      'pythonpath': ['/usr/bin', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages'],
                      'server_id': 1360107821,
                      'saltpath': '/usr/lib/python2.7/site-packages/salt',
                      'zfs_feature_flags': False,
                      'osmajorrelease': 7,
                      'swap_total': 999,
                      'os_family': 'RedHat',
                      'oscodename': 'CentOS Linux 7 (Core)',
                      'osfinger': 'CentOS Linux-7',
                      'pythonversion': [2, 7, 5, 'final', 0],
                      'manufacturer': 'innotek GmbH',
                      'mygrain': 'grain ttest value',
                      'ip4_gw': '10.0.2.2',
                      'num_gpus': 1,
                      'kernelversion': '#1 SMP Mon Jan 25 22:07:14 UTC 2016',
                      'host': 'devops',
                      'disks': ['sda', 'dm-0', 'dm-1'],
                      'cpu_model': 'Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz',
                      'uuid': '9d20bd59-85b4-47d0-83bb-6d9fac6cbba3',
                      'biosreleasedate': '12/01/2006',
                      'productname': 'VirtualBox',
                      'osarch': 'x86_64',
                      'cpuarch': 'x86_64',
                      'lsb_distrib_codename': 'CentOS Linux 7 (Core)',
                      'osrelease_info': [7, 2, 1511],
                      'locale_info': {'detectedencoding': 'UTF-8', 'defaultlanguage': 'en_GB', 'defaultencoding': 'UTF-8'},
                      'gpus': [{'model': 'VirtualBox Graphics Adapter', 'vendor': 'unknown'}],
                      'path': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin',
                      'machine_id': 'e147b422673549a3b4fda77127bd4bcd',
                      'os': 'CentOS', 'pythonexecutable': '/usr/bin/python'}}]}

_data = data['return'][0]['devops']
print('{} {} {}'.format(_data['os'],'.'.join(str(x) for x in _data['osrelease_info']), _data['osarch']))

